workflows:
  expo-app:
    name: Expo App Build
    max_build_duration: 120
    environment:
      vars:
        EXPO_SDK_VERSION: "latest" # Change to your Expo SDK version if needed
      node: latest
      npm: latest
      groups:
        - google_play # For publishing to Google Play
        - app_store   # For publishing to the App Store

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Login to Expo (optional)
        script: |
          if [ -n "$EXPO_TOKEN" ]; then
            npx expo login --non-interactive --username "$EXPO_USERNAME" --password "$EXPO_PASSWORD"
          fi

      - name: Build Android APK/AAB
        script: eas build --platform android --profile production --non-interactive

      - name: Build iOS App
        script: eas build --platform ios --profile production --non-interactive

    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/ios/**/*.ipa

    publishing:
      email:
        recipients:
          - "your-email@example.com"
