workflows:
  expo-app:
    name: Expo App Build
    max_build_duration: 120
    environment:
      vars:
        EXPO_SDK_VERSION: "latest" # Change to your Expo SDK version if needed
        EXPO_TOKEN: "owPt2rj62uNyHvqNU9L3O53OMT524NjXlxUT89AS" # Inserted your token here (not recommended for security)
      node: latest
      npm: latest
      groups:
        - google_play # For publishing to Google Play
        - app_store   # For publishing to the App Store

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Install EAS CLI
        script: npm install -g eas-cli

      - name: Authenticate with Expo
        script: |
          if [ -n "$EXPO_TOKEN" ]; then
            echo "Using EXPO_TOKEN for authentication."
          else
            echo "EXPO_TOKEN is missing. Please set it in Codemagic environment variables."
            exit 1
          fi

      - name: Build Android APK/AAB
        script: eas build --platform android --profile production --non-interactive

      - name: Build iOS App
        script: eas build --platform ios --profile production --non-interactive

    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/ios/**/*.ipa

    publishing:
      email:
        recipients:
          - "your-email@example.com"
